[package]
name="gtest"
version="1.11.0"
description="GoogleTest - Google Testing and Mocking Framework"
src={git="https://github.com/google/googletest.git", commit="e2239ee"}

[lib]
headers=["./googletest/include", "./googletest"]
builds=["./googletest/src/gtest-all.cc"]
opt=["-pthread"]
